version: "3"
services:
  php72:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: php-72
    ports:
      - "127.0.0.1:9172:9000"
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9072 start_with_request=yes idekey=VSCODE var_display_max_depth=-1 var_display_max_data=-1
    restart: always
    volumes:
      - /var/www/:/var/www/
networks:
  internal:
    driver: bridge